version: '3.8'

services:
  backend:
    image: node:18
    container_name: lance_job_backend
    working_dir: /app/backend
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
      - elasticsearch
    environment:
      - MONGO_URI=mongodb://root:projet123@mongodb:27017/lance_job?authSource=admin
      - REDIS_URI=redis://redis:6379
      - ELASTICSEARCH_URI=http://elasticsearch:9200
      - NODE_ENV=development
    command: >
      bash -c "npm install && npm run dev"
    networks:
      - lance_job_network

  frontend:
    image: node:18
    container_name: lance_job_frontend
    working_dir: /app/frontend
    volumes:
      - ./:/app/
    ports:
      - "5000:5000"
    depends_on:
      - backend
    command: >
      bash -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - lance_job_network

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: projet123
    networks:
      - lance_job_network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - lance_job_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - lance_job_network

volumes:
  mongo_data:
  redis_data:
  es_data:

networks:
  lance_job_network:
    driver: bridge